source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.1"

gem "bootsnap", require: false
gem "cssbundling-rails"
gem "pg", "~> 1.4.3"
gem "puma", "~> 5.6.5"
gem "rails", "~> 7.0.3", ">= 7.0.3.1"
gem "rack-cors"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"


# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test, :staging do
  gem "factory_bot_rails"
  gem "faker"
end

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails"
  gem "spring-commands-rspec"
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rubocop', require: false
  gem "spring"
end

group :test do
  gem "capybara"
end
