source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.1"

gem "bootsnap", require: false
gem "cssbundling-rails"
gem "jwt"
gem "pg", "~> 1.4.3"
gem "puma", "~> 5.6.5"
gem "rails", "~> 7.0.3", ">= 7.0.3.1"
gem "rack-cors"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :development, :test, :staging do
  gem "factory_bot_rails"
  gem "faker"
end

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails"
  gem "spring-commands-rspec"
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem "dotenv-rails"
  gem 'rubocop', require: false
  gem "spring"
end

group :test do
  gem "capybara"
end
